# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=django.utils.timezone.now, max_length=100, verbose_name='CONTENT'),
            preserve_default=False,
        ),
    ]
