# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='CONTENT'),
        ),
    ]
