# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20171023_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='filtered_image',
            field=models.ImageField(null=True, upload_to='upload/%Y/%m/%d/filtered'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='upload/%Y/%m/%d/orig'),
        ),
    ]
