# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20171024_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='filtered_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/upload/%Y/%m/%d/filtered'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/upload/%Y/%m/%d/orig'),
        ),
    ]
