# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 05:09
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20171028_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
