# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_auto_20171107_0358'),
        ('board', '0012_auto_20171107_1858'),
    ]

    operations = [
    ]
