# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 05:33
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_merge_20171108_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
